#A code that displays information of a student on the terminal/screen.

first_name = input("First name:")
surname = input("Surname:")
date_of_birth = input("Date of Birth:")
country = input("Country:")
city = input("City:")
email = input("Email:")
street_address = input("Street Address:")
college = input("College:")
programme_of_study = input("Programme of Study:")
parent_name = input("Parent name:")
parent_contact = input("Parent contact:")

print("First name:", first_name)
print("Surname:", surname)
print("Date of Birth:", date_of_birth)
print("Country:", country)
print("City:", city)
print("Email:", email)
print("Street address:", street_address)
print("College:", college)
print("Programme of Study:", programme_of_study)
print("Parent name:", parent_name)
print("Parent contact:", parent_contact)
